server:
 port: 8222
spring:
 application:
   name: service-gateway
 cloud:
   gateway:
     discovery:
      locator:
       enabled: true # 这个配不配都行
     routes:
       - id: service-hosp1
         uri: lb://service-hosp
         predicates:
          - Path=/*/hospital/** # 路径匹配
       - id: service-hosp2
         uri: lb://service-hosp
         predicates:
           - Path=/*/hosp/** # 路径匹配
       - id: service-hosp3
         uri: lb://service-hosp
         predicates:
           - Path=/*/user/** # 路径匹配
       - id: service-cmn
         uri: lb://service-cmn
         predicates:
          - Path=/*/cmn/** # 路径匹配
 nacos:
   discovery:
     server-addr: 127.0.0.1:8848